name: GNNImplicitSolventAndTools
channels:
  - conda-forge
dependencies:
  - ipython
  - python=3.10
  - rdkit >=2024.09.1
  - pytorch
  - ca-certificates
  - openssl
  - scikit-learn
  - openff-toolkit
  - openmmforcefields
  - certifi
  - openmm-torch=1.4
  - openmoltools
  - h5py
  - numba
  - pytorch_geometric
  - pytorch_cluster
  - pytorch_scatter
  - pytorch_sparse
  - seaborn
  - nglview
  - pyemma
  - jupyter
  - jupysql
  - sqlalchemy
  - pytest
  - tqdm
  - click
  - psycopg
  - openssl=3.4
  - pot
  - postgresql
  - rdkit-postgresql
  - pip:
    - dash